"""customer telegram nullable

Revision ID: 1dc5eb823803
Revises: 8a891d96249e
Create Date: 2026-06-16 23:10:56.772269+05:00
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dc5eb823803'
down_revision: str | None = '8a891d96249e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('telegram_id',
               existing_type=sa.BIGINT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('telegram_id',
               existing_type=sa.BIGINT(),
               nullable=False)

    # ### end Alembic commands ###
