"""payme transactions

Revision ID: 8a891d96249e
Revises: 0b6c99ff861d
Create Date: 2026-06-16 22:53:42.957703+05:00
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a891d96249e'
down_revision: str | None = '0b6c99ff861d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payme_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paycom_id', sa.String(length=60), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.BigInteger(), nullable=False),
    sa.Column('perform_time', sa.BigInteger(), nullable=False),
    sa.Column('cancel_time', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payme_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payme_transactions_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payme_transactions_paycom_id'), ['paycom_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payme_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payme_transactions_paycom_id'))
        batch_op.drop_index(batch_op.f('ix_payme_transactions_order_id'))

    op.drop_table('payme_transactions')
    # ### end Alembic commands ###
